version: "{branch} {build}"

#image: Previous Visual Studio 2015

install:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 
build:
  verbosity: detailed

build_script:
  - gradlew.bat --info --no-daemon check rubyTest

cache:
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  # - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

test: off

matrix:
  fast_finish: true

##on_finish:
 # - handle.exe -a -u C:\projects\embulk\embulk-cli\build\classes\test\org\embulk\cli\call-selfrun.bat -nobanner
